### ISSUE TITLE
calculate values on existing features

### ISSUE THREAD

**Issue by brusspi** [gacarrillor/AutoFields#1]
When creating an AutoField, it does not calculate the existing values. It only updates when you add/change values.  It would be verry nice if there was an opportunity to fix it that way.

**Comment by gacarrillor** [comment]
Thanks for the suggestion. It makes a lot of sense. 

It has been added to v0.4.0. You can access the corresponding ZIP file [here](https://github.com/gacarrillor/AutoFields/releases/tag/0.4.0) (you would need to run `make` before using it) or wait until QGIS people publish the new version of the plugin (it may take from hours to days).

Feel free to submit any other suggestion you have.
