### ISSUE TITLE
Saving Fields Definitions to File

### ISSUE THREAD

**Issue by HBConcepts** [gacarrillor/AutoFields#2]
I was wondering if it would be possible to save the definitions to a separate file so that it would persist across QGIS installs. For example, I use QGIS on both a desktop and a Laptop, with the project and layer files synched through Dropbox. The only thing that doesn't follow cleanly is the AutoFields, which I have to update on both machines whenever I make a change to an AutoField. Saving them to a file and loading them on QGIS start would solve that issue. It would also be much easier to backup and restore. Choosing the file location would be great, but saving to the same folder as the project file would also work.

**Comment by gacarrillor** [comment]
Have a look at the new version of AutoFields (v0.5.0). There is a new functionality for exporting/importing AutoFields to/from JSON files. Let me know if that solves this issue.

**Comment by HBConcepts** [comment]
Thank you. I’m going to be out of the office for the next couple of weeks, so I won’t be able to try it out right away, but from the description, it looks great!

Thanks!
