### ISSUE TITLE
Autofields Plugin does not start on QGIS python console

### ISSUE THREAD

**Issue by Lisandro79** [gacarrillor/AutoFields#6]
Hi German,

I have succesfully installed Autofields and the GUI is working perfectly well. However, when I try to use your code example in QGIS python console:

```
def getAutoFieldsManager():
    if not utils.isPluginLoaded('AutoFields'):
        if 'AutoFields' in utils.available_plugins:
            utils.loadPlugin('AutoFields')
            utils.startPlugin('AutoFields')
            af = utils.plugins['AutoFields']
            return af.autoFieldManager
        else:
            print "It seems AutoFields plugin is not installed. Could you please check it?"
            return None
```

Then 

`utils.startPlugin('AutoFields')`

returns "False". And when I call

`afm = getAutoFieldsManager()
`

afm is "None".

Any ideas on what could be wrong with `utils.startPlugin('AutoFields')` and "Autofields"?

Thanks a lot

Cheers

**Comment by gacarrillor** [comment]
Hi Lisandro,

Perhaps the plugin is already loaded and active in QGIS, so you could simply use:

    from qgis import utils
    af = utils.plugins['AutoFields']
    afm = af.autoFieldManager

Let me know if that works.

**Comment by Lisandro79** [comment]
Hi German,

You are right. The plugin is loaded and active even when I just start QGIS, your snippet of code works if I run it just after starting QGIS. Sorry for the bother and thanks for the fast response.

Cheers

**Comment by gacarrillor** [comment]
No problem. If you find the plugin useful, remember to star it in GitHub, it's a great way to give something back to the devs of your favourite software.

Regards, 

Germán
