### ISSUE TITLE
It doesn't install in QGIS 3.10.4

### ISSUE THREAD

**Issue by piretro** [gacarrillor/AutoFields#8]
It seems that Python version is changed and maybe qgis import methods too therefore some updating is needed in AutoFields code

I was able to fix line #165 in AutoFields.py to Python 3.7 syntax 
except ValueError as e:

but a new error which I am not able to fix popped up:
ModuleNotFoundError: No module named 'AutoFields-0' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'AutoFields-0'

**Comment by gacarrillor** [comment]
AutoFields is not supported for QGIS v3.x.
The functionality comes now within QGIS core.
